export interface Country {
  name: string
  capital: string
}
export const countries: Country[] = [
  { name: 'Afghanistan', capital: 'Kabul' },
  { name: 'Ägypten', capital: 'Kairo' },
  { name: 'Albanien', capital: 'Tirana' },
  { name: 'Algerien', capital: 'Algier' },
  { name: 'Andorra', capital: 'Andorra la Vella' },
  { name: 'Angola', capital: 'Luanda' },
  { name: 'Antigua und Barbuda', capital: `St. John's` },
  { name: 'Äquatorialguinea', capital: 'Malabo' },
  { name: 'Argentinien', capital: 'Buenos Aires' },
  { name: 'Armenien', capital: 'Jerewan' },
  { name: 'Aserbaidschan', capital: 'Baku' },
  { name: 'Äthiopien', capital: 'Addis Abeba' },
  { name: 'Australien', capital: 'Canberra' },
  { name: 'Bahamas', capital: 'Nassau' },
  { name: 'Bahrain', capital: 'Manama' },
  { name: 'Bangladesch', capital: 'Dhaka' },
  { name: 'Barbados', capital: 'Bridgetown' },
  { name: 'Belgien', capital: 'Brüssel' },
  { name: 'Belize', capital: 'Belmopan' },
  { name: 'Benin', capital: 'Porto Novo' },
  { name: 'Bhutan', capital: 'Thimphu' },
  { name: 'Bolivien', capital: 'Sucre' },
  { name: 'Bosnien und Herzegowina', capital: 'Sarajevo' },
  { name: 'Botsuana', capital: 'Gaborone' },
  { name: 'Brasilien', capital: 'Brasilia' },
  { name: 'Brunei', capital: 'Bandar Seri Begawan' },
  { name: 'Bulgarien', capital: 'Sofia' },
  { name: 'Burkina Faso', capital: 'Ouagadougou' },
  { name: 'Burundi', capital: 'Bujumbura' },
  { name: 'Chile', capital: 'Santiago de Chile' },
  { name: 'China', capital: 'Peking' },
  { name: 'Costa Rica', capital: 'San Jose' },
  { name: 'Dänemark', capital: 'Kopenhagen' },
  { name: 'Deutschland', capital: 'Berlin' },
  { name: 'Dominica', capital: 'Roseau' },
  { name: 'Dominikanische Republik', capital: 'Santo Domingo' },
  { name: 'Dschibuti', capital: 'Dschibuti' },
  { name: 'Ecuador', capital: 'Quito' },
  { name: 'El Salvador', capital: 'San Salvador' },
  { name: 'Elfenbeinküste', capital: 'Yamoussoukro' },
  { name: 'Eritrea', capital: 'Asmara' },
  { name: 'Estland', capital: 'Tallinn' },
  { name: 'Fidschi', capital: 'Suva' },
  { name: 'Finnland', capital: 'Helsinki' },
  { name: 'Frankreich', capital: 'Paris' },
  { name: 'Gabun', capital: 'Libreville' },
  { name: 'Gambia', capital: 'Banjul' },
  { name: 'Georgien', capital: 'Tiflis' },
  { name: 'Ghana', capital: 'Accra' },
  { name: 'Grenada', capital: `St. George's` },
  { name: 'Griechenland', capital: 'Athen' },
  { name: 'Guatemala', capital: 'Guatemala-Stadt' },
  { name: 'Guinea', capital: 'Conakry' },
  { name: 'Guinea-Bissau', capital: 'Bissau' },
  { name: 'Guyana', capital: 'Georgetown' },
  { name: 'Haiti', capital: 'Port-au-Prince' },
  { name: 'Honduras', capital: 'Tegucigalpa' },
  { name: 'Indien', capital: 'Neu-Delhi' },
  { name: 'Indonesien', capital: 'Jakarta' },
  { name: 'Irak', capital: 'Bagdad' },
  { name: 'Iran', capital: 'Teheran' },
  { name: 'Irland', capital: 'Dublin' },
  { name: 'Island', capital: 'Reykjavik' },
  { name: 'Israel', capital: 'Jerusalem' },
  { name: 'Italien', capital: 'Rom' },
  { name: 'Jamaika', capital: 'Kingston' },
  { name: 'Japan', capital: 'Tokio' },
  { name: 'Jemen', capital: 'Sanaa' },
  { name: 'Jordanien', capital: 'Amman' },
  { name: 'Kambodscha', capital: 'Phnom Penh' },
  { name: 'Kamerun', capital: 'Jaunde' },
  { name: 'Kanada', capital: 'Ottawa' },
  { name: 'Kap Verde', capital: 'Praia' },
  { name: 'Kasachstan', capital: 'Astana' },
  { name: 'Katar', capital: 'Doha' },
  { name: 'Kenia', capital: 'Nairobi' },
  { name: 'Kirgisistan', capital: 'Bischkek' },
  { name: 'Kiribati', capital: 'South Tarawa' },
  { name: 'Kolumbien', capital: 'Bogota' },
  { name: 'Komoren', capital: 'Moroni' },
  { name: 'Kongo, Demokratische Republik', capital: 'Kinshasa' },
  { name: 'Kongo, Republik', capital: 'Brazzaville' },
  { name: 'Korea Nord', capital: 'Pjöngjang' },
  { name: 'Korea Süd', capital: 'Seoul' },
  { name: 'Kosovo', capital: 'Pristina' },
  { name: 'Kroatien', capital: 'Zagreb' },
  { name: 'Kuba', capital: 'Havanna' },
  { name: 'Kuwait', capital: 'Kuwait-Stadt' },
  { name: 'Laos', capital: 'Vientiane' },
  { name: 'Lesotho', capital: 'Maseru' },
  { name: 'Lettland', capital: 'Riga' },
  { name: 'Libanon', capital: 'Beirut' },
  { name: 'Liberia', capital: 'Monrovia' },
  { name: 'Libyen', capital: 'Tripolis' },
  { name: 'Lichtenstein', capital: 'Vaduz' },
  { name: 'Litauen', capital: 'Vilnius' },
  { name: 'Luxemburg', capital: 'Luxemburg' },
  { name: 'Madagaskar', capital: 'Antananarivo' },
  { name: 'Malawi', capital: 'Lilongwe' },
  { name: 'Malaysia', capital: 'Kuala Lumpur' },
  { name: 'Malediven', capital: 'Male' },
  { name: 'Mali', capital: 'Bamako' },
  { name: 'Malta', capital: 'Valletta' },
  { name: 'Marokko', capital: 'Rabat' },
  { name: 'Marshallinseln', capital: 'Majuro' },
  { name: 'Mauretanien', capital: 'Nouakchott' },
  { name: 'Mauritius', capital: 'Port Louis' },
  { name: 'Mazedonien', capital: 'Skopje' },
  { name: 'Mexiko', capital: 'Mexiko-Stadt' },
  { name: 'Mikronesien', capital: 'Palikir' },
  { name: 'Moldawien', capital: 'Chisinau' },
  { name: 'Monaco', capital: 'Monaco' },
  { name: 'Mongolei', capital: 'Ulaanbaatar' },
  { name: 'Montenegro', capital: 'Podgorica' },
  { name: 'Mosambik', capital: 'Maputo' },
  { name: 'Myanmar', capital: 'Pyinmana Naypyidaw' },
  { name: 'Namibia', capital: 'Windhoek' },
  { name: 'Nauru', capital: 'Yaren' },
  { name: 'Nepal', capital: 'Kathmandu' },
  { name: 'Neuseeland', capital: 'Wellington' },
  { name: 'Nicaragua', capital: 'Managua' },
  { name: 'Niederlande', capital: 'Amsterdam' },
  { name: 'Niger', capital: 'Niamey' },
  { name: 'Nigeria', capital: 'Abuja' },
  { name: 'Norwegen', capital: 'Oslo' },
  { name: 'Oman', capital: 'Maskat' },
  { name: 'Österreich', capital: 'Wien' },
  { name: 'Osttimor', capital: 'Dili' },
  { name: 'Pakistan', capital: 'Islamabad' },
  { name: 'Palau', capital: 'Melekeok' },
  { name: 'Panama', capital: 'Panama-Stadt' },
  { name: 'Papua-Neuguinea', capital: 'Port Moresby' },
  { name: 'Paraguay', capital: 'Asuncion' },
  { name: 'Peru', capital: 'Lima' },
  { name: 'Philippinen', capital: 'Manila' },
  { name: 'Polen', capital: 'Warschau' },
  { name: 'Portugal', capital: 'Lissabon' },
  { name: 'Ruanda', capital: 'Kigali' },
  { name: 'Rumänien', capital: 'Bukarest' },
  { name: 'Russland', capital: 'Moskau' },
  { name: 'Salomonen', capital: 'Honiara' },
  { name: 'Sambia', capital: 'Lusaka' },
  { name: 'Samoa', capital: 'Apia' },
  { name: 'San Marino', capital: 'San Marino' },
  { name: 'Saudi-Arabien', capital: 'Riad' },
  { name: 'Schweden', capital: 'Stockholm' },
  { name: 'Schweiz', capital: 'Bern' },
  { name: 'Senegal', capital: 'Dakar' },
  { name: 'Serbien', capital: 'Belgrad' },
  { name: 'Seychellen', capital: 'Victoria' },
  { name: 'Sierra Leone', capital: 'Freetown' },
  { name: 'Simbabwe', capital: 'Harare' },
  { name: 'Singapur', capital: 'Singapur' },
  { name: 'Slowakei', capital: 'Bratislava' },
  { name: 'Slowenien', capital: 'Ljubljana' },
  { name: 'Somalia', capital: 'Mogadischu' },
  { name: 'Spanien', capital: 'Madrid' },
  { name: 'Sri Lanka', capital: 'Colombo' },
  { name: 'St. Kitts und Nevis', capital: 'Basseterre' },
  { name: 'Sl. Lucia', capital: 'Castries' },
  { name: 'St. Vincent und die Grenadinen', capital: 'Kingstown' },
  { name: 'Südafrika', capital: 'Pretoria' },
  { name: 'Sudan', capital: 'Khartum' },
  { name: 'Südsudan', capital: 'Juba' },
  { name: 'Suriname', capital: 'Paramaribo' },
  { name: 'Swasiland', capital: 'Mbabane' },
  { name: 'Syrien', capital: 'Damaskus' },
  { name: 'Sao Tome und Principe', capital: 'Sao Tome' },
  { name: 'Tadschikistan', capital: 'Duschanbe' },
  { name: 'Tansania', capital: 'Dodoma' },
  { name: 'Thailand', capital: 'Bangkok' },
  { name: 'Togo', capital: 'Lome' },
  { name: 'Tonga', capital: `Nuku'alofa` },
  { name: 'Trinidad und Tobago', capital: 'Port-of-Spain' },
  { name: 'Tschad', capital: `N'Djamena` },
  { name: 'Tschechien', capital: 'Prag' },
  { name: 'Tunesien', capital: 'Tunis' },
  { name: 'Türkei', capital: 'Ankara' },
  { name: 'Turkmenistan', capital: 'Aschgabat' },
  { name: 'Tuvalu', capital: 'Funafuti' },
  { name: 'Uganda', capital: 'Kampala' },
  { name: 'Ukraine', capital: 'Kiew' },
  { name: 'Ungarn', capital: 'Budapest' },
  { name: 'Uruguay', capital: 'Montevideo' },
  { name: 'Usbekistan', capital: 'Taschkent' },
  { name: 'Vanuatu', capital: 'Port Vila' },
  { name: 'Vatikanstadt', capital: 'keine' },
  { name: 'Venezuela', capital: 'Caracas' },
  { name: 'Vereinigte Arabische Emirate', capital: 'Abu Dhabi' },
  { name: 'Vereinigte Staaten von Amerika', capital: 'Washington' },
  { name: 'Vereinigtes Königreich', capital: 'London' },
  { name: 'Vietnam', capital: 'Hanoi' },
  { name: 'Weißrussland', capital: 'Minsk' },
  { name: 'Zentralafrikanische Republik', capital: 'Bangui' },
  { name: 'Zypern', capital: 'Nikosia' },
]
